#!/bin/bash

if [ ! -e ./.env ]; then
    cp -f .env.sample .env
fi

if [ ! -e ./compose.d/.dist ]; then
    mkdir ./compose.d/.dist
fi

. .env
rm -f ./compose.d/.dist/*.yml

ymls=''
for c_env in ${COMPOSE_ENV[@]}; do

    export PREFIX=$c_env
    for file in `ls -1 ./compose.d/$c_env/*.yml`; do
        . ./compose.d/$c_env/value.sh

        dist_path="./compose.d/.dist/${c_env}_${file##*/}"
        envsubst < $file > $dist_path
    done

done

for file in `ls -1 ./compose.d/.dist/*.yml`; do
    ymls="-f $file $ymls"
done


up () {
    if [ "$COMPOSE_BUILD_ENABLE" == "true" ]; then
        build
    fi

    eval "docker-compose $ymls up -d"
}

down () {
    eval "docker-compose $ymls down"
}

build () {
    eval "docker-compose $ymls build"
}

case $1 in
    "up")
        up
    ;;
    "down")
        down
    ;;
    "build")
        build
    ;;
esac
