version: "3"
services:
  app1:
    image: alpine
    restart: on-failure
    environment:
      TZ:
      SERVICE_HOST:
      SERVICE_DOMAIN:
      SERVICE_URL: "${SERVICE_DOMAIN}/foo/app1"
    command: /bin/sh -c "while :; do sleep 10; done"
